language: node_js
node_js:
  - 0.10
  - 0.8
  - 0.6
notifications:
  irc: "irc.freenode.org#greenfinity"
before_script:
  - "export DISPLAY=:99:0"
  - "echo 'Starting buster server'"
  - "./node_modules/buster/bin/buster-server &"
  - "sleep 3"
  - "echo 'Done.'"
  - "echo 'Starting phantomjs server'"
  - "phantomjs ./node_modules/buster/script/phantom.js &"
  - "sleep 3"
  - "echo 'Done.'"